/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ge.connect;

public class Library {
    // Comment
    public boolean someLibraryMethod() {
        return true;
    }
}
